# Generated by Django 4.2.29 on 2026-04-27 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the service/item (e.g., Captain, Juice)', max_length=255, unique=True)),
                ('default_price', models.DecimalField(decimal_places=2, default=0.0, help_text='Default price/rate for manual invoices', max_digits=10)),
                ('order', models.IntegerField(default=0, help_text='Order in the dropdown lists')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TermAndCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='The actual term or condition rule.')),
                ('order', models.IntegerField(default=0, help_text='Order in which this term appears.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
