# Generated by Django 4.2.29 on 2026-03-25 03:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import staff.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('staff_id', models.CharField(default=staff.models.generate_staff_id, max_length=20, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='staff/')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('chef', 'Chef'), ('server', 'Server / Waiter'), ('driver', 'Driver'), ('cleaner', 'Cleaner'), ('other', 'Other')], default='server', max_length=20)),
                ('daily_rate', models.DecimalField(decimal_places=2, default=0, help_text='Daily wage in ₹', max_digits=8)),
                ('commission_pct', models.DecimalField(decimal_places=2, default=0, help_text='% of booking value as commission', max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('joined_at', models.DateField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Staff Member',
                'verbose_name_plural': 'Staff Members',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='StaffPayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payout_type', models.CharField(choices=[('salary', 'Monthly Salary'), ('daily_wage', 'Daily Wage'), ('commission', 'Event Commission'), ('bonus', 'Bonus'), ('advance', 'Advance')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='pending', max_length=15)),
                ('paid_on', models.DateField(blank=True, null=True)),
                ('paid_by', models.CharField(blank=True, help_text='Admin who approved the payment', max_length=200)),
                ('reference', models.CharField(blank=True, help_text='UPI ref / bank transfer ID', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payouts', to='bookings.booking')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StaffAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('half_day', 'Half Day')], default='present', max_length=10)),
                ('hours', models.DecimalField(decimal_places=1, default=8, max_digits=4)),
                ('notes', models.TextField(blank=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_attendance', to='bookings.booking')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('staff', 'date', 'booking')},
            },
        ),
    ]
