# Generated by Django 4.2.29 on 2026-03-26 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('chef', 'Chef'), ('server', 'Server / Waiter'), ('driver', 'Driver'), ('cleaner', 'Cleaner'), ('other', 'Other')], db_index=True, default='server', max_length=20),
        ),
        migrations.AlterField(
            model_name='staffattendance',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='staffattendance',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('half_day', 'Half Day')], db_index=True, default='present', max_length=10),
        ),
        migrations.AlterField(
            model_name='staffpayout',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=15),
        ),
    ]
