# Generated by Django 4.2.29 on 2026-03-26 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_alter_staff_is_active_alter_staff_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffattendance',
            name='reaching_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
