# Generated by Django 4.2.29 on 2026-03-27 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_staffattendance_reaching_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('service', models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('chef', 'Chef'), ('server', 'Server / Waiter'), ('driver', 'Driver'), ('cleaner', 'Cleaner'), ('other', 'Other')], max_length=20)),
                ('age', models.PositiveIntegerField()),
                ('height', models.CharField(help_text='e.g. 5\'9"', max_length=20)),
                ('blood_group', models.CharField(max_length=10)),
                ('phone_1', models.CharField(max_length=20)),
                ('phone_2', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('place', models.CharField(max_length=255)),
                ('education', models.CharField(max_length=255)),
                ('aadhar_card_no', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
