# Generated by Django 4.2.29 on 2026-03-27 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_staffapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffapplication',
            name='guardian_name',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staffapplication',
            name='guardian_phone',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
