# Generated by Django 4.2.29 on 2026-03-27 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0006_staff_aadhar_card_no_staff_age_staff_blood_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffapplication',
            name='status',
            field=models.CharField(choices=[('unverified', 'Unverified Phone'), ('pending', 'Pending Admin Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='unverified', max_length=15),
        ),
    ]
