# Generated by Django 4.2.29 on 2026-03-29 12:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0007_alter_staffapplication_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='role',
        ),
        migrations.RemoveField(
            model_name='staffapplication',
            name='service',
        ),
        migrations.AddField(
            model_name='staff',
            name='level',
            field=models.CharField(choices=[('admin', 'Admin'), ('A', 'A Level'), ('B', 'B Level'), ('C', 'C Level')], db_index=True, default='C', max_length=20),
        ),
        migrations.AddField(
            model_name='staff',
            name='total_events_completed',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='PromotionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_level', models.CharField(max_length=10)),
                ('requested_level', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
