# Generated by Django 4.2.29 on 2026-03-29 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0008_remove_staff_role_remove_staffapplication_service_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='level',
            field=models.CharField(choices=[('A', 'A Level'), ('B', 'B Level'), ('C', 'C Level'), ('caption', 'Caption'), ('admin', 'Admin')], db_index=True, default='C', max_length=20),
        ),
    ]
