# Generated by Django 4.2.29 on 2026-03-29 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0009_alter_staff_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='level',
            field=models.CharField(choices=[('A', 'A Level'), ('B', 'B Level'), ('C', 'C Level'), ('captain', 'Captain'), ('admin', 'Admin')], db_index=True, default='C', max_length=20),
        ),
    ]
