# Generated by Django 4.2.29 on 2026-03-29 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0010_alter_staff_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='main_locality',
            field=models.CharField(blank=True, choices=[('Kondotty', 'Kondotty'), ('Areekode', 'Areekode'), ('Edavannappara', 'Edavannappara'), ('Kizhisseri', 'Kizhisseri'), ('University', 'University'), ('Valluvambram', 'Valluvambram')], help_text='Major operational area', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='place',
            field=models.CharField(blank=True, help_text='Specific city/town details', max_length=255),
        ),
    ]
