# Generated by Django 4.2.29 on 2026-03-30 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0011_staff_main_locality_alter_staff_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffapplication',
            name='main_locality',
            field=models.CharField(blank=True, choices=[('Kondotty', 'Kondotty'), ('Areekode', 'Areekode'), ('Edavannappara', 'Edavannappara'), ('Kizhisseri', 'Kizhisseri'), ('University', 'University'), ('Valluvambram', 'Valluvambram')], help_text='Major operational area', max_length=50, null=True),
        ),
    ]
