# Generated by Django 4.2.29 on 2026-04-07 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0012_staffapplication_main_locality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotionrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Not Approved')], db_index=True, default='pending', max_length=15),
        ),
        migrations.AlterField(
            model_name='staffapplication',
            name='status',
            field=models.CharField(choices=[('unverified', 'Unverified Phone'), ('pending', 'Pending Admin Review'), ('approved', 'Approved'), ('rejected', 'Not Approved')], db_index=True, default='unverified', max_length=15),
        ),
    ]
