# Generated by Django 4.2.29 on 2026-04-07 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0013_alter_promotionrequest_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffattendance',
            name='payment_given',
            field=models.BooleanField(default=False),
        ),
    ]
