# Generated by Django 4.2.29 on 2026-04-14 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0014_staffattendance_payment_given'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_active', models.BooleanField(default=True, help_text='Show this notice on the staff portal front page')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
