# Generated by Django 4.2.29 on 2026-04-14 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0015_staffnotice'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='coat_size',
            field=models.CharField(blank=True, choices=[('S', 'Small (S)'), ('M', 'Medium (M)'), ('L', 'Large (L)'), ('XL', 'Extra Large (XL)'), ('XXL', 'Double XL (XXL)')], help_text='Required coat size', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='staffapplication',
            name='coat_size',
            field=models.CharField(blank=True, choices=[('S', 'Small (S)'), ('M', 'Medium (M)'), ('L', 'Large (L)'), ('XL', 'Extra Large (XL)'), ('XXL', 'Double XL (XXL)')], max_length=5, null=True),
        ),
    ]
