# Generated by Django 4.2.29 on 2026-04-19 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0016_staff_coat_size_staffapplication_coat_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffattendance',
            name='notes',
        ),
        migrations.AddField(
            model_name='staffattendance',
            name='grooming',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='staffattendance',
            name='on_time',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='staffattendance',
            name='shoes',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='staffattendance',
            name='uniform',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='staffattendance',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('absent', 'Absent')], db_index=True, default='present', max_length=10),
        ),
    ]
