# Generated by Django 4.2.29 on 2026-04-20 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0017_remove_staffattendance_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='must_change_password',
            field=models.BooleanField(default=False, help_text='Force this staff member to change their password on next login.'),
        ),
    ]
