# Generated by Django 4.2.29 on 2026-04-21 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0018_must_change_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffattendance',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('present', 'Present'), ('absent', 'Absent')], db_index=True, default='pending', max_length=10),
        ),
    ]
