# Generated by Django 4.2.29 on 2026-04-25 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0020_fcmdevice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staffapplication',
            old_name='place',
            new_name='home_address',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='aadhar_card_no',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='age',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='place',
        ),
        migrations.RemoveField(
            model_name='staffapplication',
            name='aadhar_card_no',
        ),
        migrations.RemoveField(
            model_name='staffapplication',
            name='age',
        ),
        migrations.AddField(
            model_name='staff',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10),
        ),
        migrations.AddField(
            model_name='staff',
            name='home_address',
            field=models.CharField(blank=True, help_text='Specific city/town/home details', max_length=255),
        ),
        migrations.AddField(
            model_name='staffapplication',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staffapplication',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Other', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='staff',
            name='education',
            field=models.CharField(blank=True, choices=[('10th', '10th'), ('+1', '+1'), ('+2', '+2'), ('UG', 'UG'), ('PG', 'PG')], max_length=50),
        ),
        migrations.AlterField(
            model_name='staffapplication',
            name='education',
            field=models.CharField(choices=[('10th', '10th'), ('+1', '+1'), ('+2', '+2'), ('UG', 'UG'), ('PG', 'PG')], max_length=50),
        ),
    ]
