# Generated by Django 4.2.29 on 2026-04-25 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0021_rename_place_staffapplication_home_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='level',
            field=models.CharField(choices=[('A', 'A Level'), ('B', 'B Level'), ('C', 'C Level'), ('supervisor', 'Supervisor'), ('captain', 'Captain'), ('admin', 'Admin')], db_index=True, default='C', max_length=20),
        ),
    ]
