# Generated by Django 4.2.29 on 2026-04-25 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0022_alter_staff_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffattendance',
            name='bonus',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Extra money given', max_digits=8),
        ),
        migrations.AddField(
            model_name='staffattendance',
            name='deduction',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount deducted', max_digits=8),
        ),
    ]
