# Generated by Django 4.2.29 on 2026-04-26 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0023_staffattendance_bonus_staffattendance_deduction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='education',
            field=models.CharField(blank=True, choices=[('+1', '+1'), ('+2', '+2'), ('UG', 'UG'), ('PG', 'PG'), ('Other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='staffapplication',
            name='education',
            field=models.CharField(choices=[('+1', '+1'), ('+2', '+2'), ('UG', 'UG'), ('PG', 'PG'), ('Other', 'Other')], max_length=50),
        ),
    ]
