# Generated by Django 4.2.29 on 2026-04-26 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0024_alter_staff_education_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='main_locality',
            field=models.CharField(blank=True, choices=[('Areekode', 'Areekode'), ('Calicut', 'Calicut'), ('Edavannappara', 'Edavannappara'), ('Farook', 'Farook'), ('Kizhisseri', 'Kizhisseri'), ('Kondotty', 'Kondotty'), ('Mavoor', 'Mavoor'), ('Manjeri', 'Manjeri'), ('Ramanattukara', 'Ramanattukara'), ('University', 'University'), ('Valluvambram', 'Valluvambram')], help_text='Major operational area', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='staffapplication',
            name='main_locality',
            field=models.CharField(blank=True, choices=[('Areekode', 'Areekode'), ('Calicut', 'Calicut'), ('Edavannappara', 'Edavannappara'), ('Farook', 'Farook'), ('Kizhisseri', 'Kizhisseri'), ('Kondotty', 'Kondotty'), ('Mavoor', 'Mavoor'), ('Manjeri', 'Manjeri'), ('Ramanattukara', 'Ramanattukara'), ('University', 'University'), ('Valluvambram', 'Valluvambram')], help_text='Major operational area', max_length=50, null=True),
        ),
    ]
