# Generated by Django 4.2.29 on 2026-04-26 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0026_alter_staff_main_locality_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Locality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Localities',
                'ordering': ['name'],
            },
        ),
    ]
