# Generated by Django 4.2.29 on 2026-04-27 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0027_locality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='main_locality',
            field=models.CharField(blank=True, help_text='Major operational area', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='staffapplication',
            name='main_locality',
            field=models.CharField(blank=True, help_text='Major operational area', max_length=50, null=True),
        ),
    ]
