# Generated by Django 4.2.29 on 2026-04-07 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_eventapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='location_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='location_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='booking',
            name='session',
            field=models.CharField(choices=[('day', 'Day'), ('night', 'Night')], default='day', max_length=10),
        ),
        migrations.AddField(
            model_name='eventapplication',
            name='note',
            field=models.TextField(blank=True, help_text='Note from staff to admin'),
        ),
        migrations.AlterField(
            model_name='eventapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Not Approved'), ('cancel_requested', 'Cancel Requested'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20),
        ),
    ]
