# Generated by Django 4.2.29 on 2026-04-07 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_booking_location_link_booking_location_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.DateField()),
                ('site_name', models.CharField(max_length=255)),
                ('event_name', models.CharField(max_length=255)),
                ('boys_count', models.IntegerField(default=0)),
                ('bill_incharge', models.CharField(max_length=255)),
                ('bill_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('amount_received', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('payment_received_on', models.DateField(blank=True, null=True)),
                ('pending_amount', models.CharField(blank=True, help_text='Can be NIL or numeric', max_length=255, null=True)),
                ('profit', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('is_settled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-event_date', '-created_at'],
            },
        ),
    ]
