# Generated by Django 4.2.29 on 2026-04-07 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_manualreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_published',
            field=models.BooleanField(default=False, help_text='If True, staff can see and apply for this event'),
        ),
        migrations.AddField(
            model_name='booking',
            name='quota_a',
            field=models.PositiveIntegerField(default=0, help_text='Number of A-Level staff needed'),
        ),
        migrations.AddField(
            model_name='booking',
            name='quota_b',
            field=models.PositiveIntegerField(default=0, help_text='Number of B-Level staff needed'),
        ),
        migrations.AddField(
            model_name='booking',
            name='quota_c',
            field=models.PositiveIntegerField(default=0, help_text='Number of C-Level staff needed'),
        ),
        migrations.AddField(
            model_name='booking',
            name='quota_captain',
            field=models.PositiveIntegerField(default=0, help_text='Number of Captains needed'),
        ),
    ]
