# Generated by Django 4.2.29 on 2026-04-09 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_booking_is_published_booking_quota_a_booking_quota_b_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='publish_locality',
            field=models.CharField(choices=[('all', 'All Localities'), ('Kondotty', 'Kondotty'), ('Areekode', 'Areekode'), ('Edavannappara', 'Edavannappara'), ('Kizhisseri', 'Kizhisseri'), ('University', 'University'), ('Valluvambram', 'Valluvambram')], default='all', help_text='Publish only to staff from this locality', max_length=50),
        ),
    ]
