# Generated by Django 4.2.29 on 2026-04-14 13:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookings', '0008_booking_publish_locality'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_in_charge', models.CharField(blank=True, default='NIL', max_length=255)),
                ('total_amount', models.CharField(blank=True, default='NIL', max_length=255)),
                ('balance_amount', models.CharField(blank=True, default='NIL', max_length=255)),
                ('pending', models.CharField(blank=True, default='NIL', max_length=255)),
                ('juice', models.CharField(blank=True, default='NIL', max_length=255)),
                ('tea', models.CharField(blank=True, default='NIL', max_length=255)),
                ('popcorn', models.CharField(blank=True, default='NIL', max_length=255)),
                ('hosting', models.CharField(blank=True, default='NIL', max_length=255)),
                ('coat_incharge', models.CharField(blank=True, default='NIL', max_length=255)),
                ('coat_rent', models.CharField(blank=True, default='NIL', max_length=255)),
                ('ta', models.CharField(blank=True, default='NIL', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='bookings.booking')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
