# Generated by Django 4.2.29 on 2026-04-15 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0010_eventtask'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='allow_direct_join',
            field=models.BooleanField(default=False, help_text='If True, staff can join instantly without admin approval.'),
        ),
    ]
