# Generated by Django 4.2.29 on 2026-04-19 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0011_booking_allow_direct_join'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventtask',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
