# Generated by Django 4.2.29 on 2026-04-19 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0012_eventtask_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventreport',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted')], default='draft', max_length=20),
        ),
    ]
