# Generated by Django 4.2.29 on 2026-04-19 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0013_eventreport_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_long_work',
            field=models.BooleanField(default=False, help_text='Checked if the venue is >20km from the main office'),
        ),
    ]
