# Generated by Django 4.2.29 on 2026-04-21 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0015_alter_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventapplication',
            name='cancel_rejected',
            field=models.BooleanField(default=False, help_text='True if admin denied a cancel request'),
        ),
    ]
