# Generated by Django 4.2.29 on 2026-04-25 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0018_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='quota_supervisor',
            field=models.PositiveIntegerField(default=0, help_text='Number of Supervisors needed'),
        ),
    ]
