# Generated by Django 4.2.29 on 2026-04-26 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0019_booking_quota_supervisor'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventreport',
            name='bottle_count',
            field=models.CharField(blank=True, default='NIL', max_length=255),
        ),
        migrations.AddField(
            model_name='eventreport',
            name='note',
            field=models.TextField(blank=True, help_text='Additional notes or message for the admin'),
        ),
        migrations.AddField(
            model_name='eventreport',
            name='plate_count',
            field=models.CharField(blank=True, default='NIL', max_length=255),
        ),
    ]
