# Generated by Django 4.2.29 on 2026-04-26 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0020_eventreport_bottle_count_eventreport_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventreport',
            name='work_type',
            field=models.CharField(choices=[('day', 'Day'), ('night', 'Night')], default='day', help_text='Was this a day or night event?', max_length=10),
        ),
        migrations.AddField(
            model_name='manualreport',
            name='work_type',
            field=models.CharField(choices=[('day', 'Day'), ('night', 'Night')], default='day', max_length=10),
        ),
    ]
