# Generated by Django 4.2.29 on 2026-04-26 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0021_eventreport_work_type_manualreport_work_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventreport',
            name='extra_logistics',
            field=models.CharField(blank=True, default='NIL', help_text='One more thing / additional field', max_length=255),
        ),
    ]
