# Generated by Django 4.2.29 on 2026-04-26 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0022_eventreport_extra_logistics'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventreport',
            name='dynamic_logistics',
            field=models.JSONField(blank=True, default=dict, help_text='Custom logistics fields added by user'),
        ),
        migrations.AddField(
            model_name='eventreport',
            name='dynamic_rentals',
            field=models.JSONField(blank=True, default=dict, help_text='Custom rental fields added by user'),
        ),
    ]
