# Generated by Django 4.2.29 on 2026-04-27 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0023_eventreport_dynamic_logistics_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='publish_locality',
            field=models.CharField(default='all', help_text='Publish only to staff from this locality', max_length=50),
        ),
    ]
