# Generated by Django 4.2.29 on 2026-04-27 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0024_alter_booking_publish_locality'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventapplication',
            name='is_double_work',
            field=models.BooleanField(default=False, help_text='True if staff already has another booking on this day (different session)'),
        ),
    ]
