# Generated by Django 4.2.29 on 2026-04-27 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0025_add_is_double_work'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='guest_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
